/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import download.Download;
import java.io.File;


public class jfActeNecesare extends javax.swing.JFrame {

    /**
     * Creates new form jfActeNecesare
     */
    public jfActeNecesare() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jbCerereDisponibilitate = new javax.swing.JButton();
        jbCerereInregistrare = new javax.swing.JButton();
        jbAnexa1 = new javax.swing.JButton();
        jCheckBox14 = new javax.swing.JCheckBox();
        jbDeclaratie = new javax.swing.JButton();
        jbAnexa2 = new javax.swing.JButton();
        jbConstitutiv = new javax.swing.JButton();
        jbDeclaratieBeneficiar = new javax.swing.JButton();

        setTitle("Acte necesare infintarii firmei");
        setLocation(new java.awt.Point(400, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Acte necesare");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Cerere de verificare disponibilitate si/sau rezervare denumire firma");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Operatiuni prealabile:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Inregistrare:");

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setText("Cerere de inregistrare(Original)");

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setText("Anexa 1 privind inregistrarea fiscala");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox4.setText("Declaratia-tip pe propria raspundere semnata de asociati sau de administratori");

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox5.setText("Dovada verificarii disponibilitatii si rezervarii denumirii firmei si, dupa caz, a emblemei");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox6.setText("Acordul pentru utilizare denumirii (Daca este cazul, prevazut de art. 39 din Legea nr. 26/1990)");

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox7.setText("Actul constitutiv (Original)");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox8.setText("Documentul care atesta dreptul de folosinta asupra spatiului cu destinatie de sediu social");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox9.setText("Actele de identitate ale fondatorilor");

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox10.setText("Specimenele de semnatura ale reprezentantilor societatii (Original)");

        jCheckBox11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox11.setText("Informatii din cazierul fiscal al asociatilor, care au obligatia prezentarii certificatului de cazier fiscal (Original)");

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox12.setText("Declaratie privind beneficiarul real al persoanei juridice");

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox13.setText("Dovezile privind plata tarifului legal");

        jButton1.setText("Iesire");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbCerereDisponibilitate.setText("Descarca document");
        jbCerereDisponibilitate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerereDisponibilitateActionPerformed(evt);
            }
        });

        jbCerereInregistrare.setText("Descarca document");
        jbCerereInregistrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerereInregistrareActionPerformed(evt);
            }
        });

        jbAnexa1.setText("Descarca document");
        jbAnexa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnexa1ActionPerformed(evt);
            }
        });

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox14.setText("Anexa 2 privind investitia straina (daca este cazul)");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jbDeclaratie.setText("Descarca document");
        jbDeclaratie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeclaratieActionPerformed(evt);
            }
        });

        jbAnexa2.setText("Descarca document");
        jbAnexa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnexa2ActionPerformed(evt);
            }
        });

        jbConstitutiv.setText("Descarca document");
        jbConstitutiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConstitutivActionPerformed(evt);
            }
        });

        jbDeclaratieBeneficiar.setText("Descarca document");
        jbDeclaratieBeneficiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeclaratieBeneficiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(564, 564, 564)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCerereDisponibilitate)
                            .addComponent(jbDeclaratieBeneficiar)
                            .addComponent(jbConstitutiv)
                            .addComponent(jCheckBox7)
                            .addComponent(jbDeclaratie)
                            .addComponent(jbAnexa2)
                            .addComponent(jCheckBox4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox12)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbAnexa1)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox14)
                                    .addComponent(jbCerereInregistrare))
                                .addGap(300, 300, 300)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox9)
                                    .addComponent(jCheckBox10)
                                    .addComponent(jCheckBox13)
                                    .addComponent(jCheckBox11)
                                    .addComponent(jCheckBox5))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(2, 2, 2)
                .addComponent(jbCerereDisponibilitate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCerereInregistrare)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(jbAnexa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAnexa2)
                    .addComponent(jCheckBox13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDeclaratie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConstitutiv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDeclaratieBeneficiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jbCerereDisponibilitateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerereDisponibilitateActionPerformed
        // TODO add your handling code here:
        String link = "https://www.onrc.ro/templates/site/formulare/11-10-182.pdf";
        File out = new File("D:\\JAVA\\IdeaProjects\\space-hack\\descarcari\\Cerere_disponibilitate.pdf");
        
        new Thread(new download.Download(link, out)).start();
    }//GEN-LAST:event_jbCerereDisponibilitateActionPerformed

    private void jbCerereInregistrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerereInregistrareActionPerformed
        // TODO add your handling code here:
        String link = "https://www.onrc.ro/templates/site/formulare/11-10-150.pdf";
        File out = new File("D:\\JAVA\\IdeaProjects\\space-hack\\descarcari\\Cerere_de_inregistrare.pdf");
        
        new Thread(new download.Download(link, out)).start();
    }//GEN-LAST:event_jbCerereInregistrareActionPerformed

    private void jbAnexa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnexa1ActionPerformed
        // TODO add your handling code here:
        String link = "https://www.onrc.ro/templates/site/formulare/anexa_1_inregistrare_fiscala.pdf";
        File out = new File("D:\\JAVA\\IdeaProjects\\space-hack\\descarcari\\Anexa_1.pdf");
        
        new Thread(new download.Download(link, out)).start();
    }//GEN-LAST:event_jbAnexa1ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jbDeclaratieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeclaratieActionPerformed
        // TODO add your handling code here:
        String link = "https://www.onrc.ro/templates/site/formulare/11-10-141.pdf";
        File out = new File("D:\\JAVA\\IdeaProjects\\space-hack\\descarcari\\Declaratie.pdf");
        
        new Thread(new download.Download(link, out)).start();
    }//GEN-LAST:event_jbDeclaratieActionPerformed

    private void jbAnexa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnexa2ActionPerformed
        // TODO add your handling code here:
        String link = "https://www.onrc.ro/templates/site/formulare/anexa_2_investitie_straina.pdf";
        File out = new File("D:\\JAVA\\IdeaProjects\\space-hack\\descarcari\\Anexa_2.pdf");
        
        new Thread(new download.Download(link, out)).start();
    }//GEN-LAST:event_jbAnexa2ActionPerformed

    private void jbConstitutivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConstitutivActionPerformed
        // TODO add your handling code here:
        String link = "https://www.onrc.ro/documente/acte_constitutive/model%20AC%20SRL%20AS.%20UNIC%20MODIFICAT.doc";
        File out = new File("D:\\JAVA\\IdeaProjects\\space-hack\\descarcari\\Actul_constitutiv.pdf");
        
        new Thread(new download.Download(link, out)).start();
    }//GEN-LAST:event_jbConstitutivActionPerformed

    private void jbDeclaratieBeneficiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeclaratieBeneficiarActionPerformed
        // TODO add your handling code here:
        String link = "https://www.onrc.ro/templates/site/formulare/declaratie%20beneficiar%20real.pdf";
        File out = new File("D:\\JAVA\\IdeaProjects\\space-hack\\descarcari\\Declaratie_privind_beneficiarii_reali.pdf");
        
        new Thread(new download.Download(link, out)).start();
    }//GEN-LAST:event_jbDeclaratieBeneficiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfActeNecesare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfActeNecesare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfActeNecesare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfActeNecesare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfActeNecesare().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbAnexa1;
    private javax.swing.JButton jbAnexa2;
    private javax.swing.JButton jbCerereDisponibilitate;
    private javax.swing.JButton jbCerereInregistrare;
    private javax.swing.JButton jbConstitutiv;
    private javax.swing.JButton jbDeclaratie;
    private javax.swing.JButton jbDeclaratieBeneficiar;
    // End of variables declaration//GEN-END:variables
}
